### ISSUE TITLE
Auto flashing does not work when performing DFU over BLE

### ISSUE THREAD

**Issue by hakonfam** [NordicSemiconductor/pc-nrfutil#21] opened 2016-06-24 08:23 UTC
Using version 5a5e418f49579bd with pc-ble-driver-py version 0.4.0, the following happens when attempting to perform a DFU over BLE with auto-flashing of the connectivity driver:

```
mypath>nrfutil dfu ble -f -p COM40 -pkg app_v1.0.0.zip
No target selected. Default device name: DfuTarg is used.
  [------------------------------------]    0%

Failed to update the target. Error is:
```

**Comment by carlescufi** [comment] 2016-06-24 08:32
The problem is that we cannot know if it was a flashing error or a transfer error. I vote to move out the flashing functionality from DfuTransportBle into __main__ so that we can be more precise in reporting

**Comment by WojciechJasko** [comment] 2016-06-24 08:57
Can you try [aa0372b](https://github.com/NordicSemiconductor/pc-nrfutil/commit/aa0372b048ebe223577f8748bd5bb905e6fe8373)

**Comment by carlescufi** [comment] 2016-06-29 11:25
This is now fixed

**Closed by carlescufi** 2016-06-29 11:25 UTC
